### ISSUE TITLE
Performance difference when replacing FFN with FMoETransformerMLP in transformer

### ISSUE THREAD

**Issue by JiawangLiu** [laekov/fastmoe#125]
As the title, when I replace FFN layer in transformer with the FMoETransformerMLP  module with one expert and data parallel mode in the pretraining task, the performance gets worse, FMoETransformerMLP  module with one expert should not be equivalent to the dense model, and what are the possible reasons for the difference, thanks!

original code :
```python
# init
self.activation_fn = torch.nn.ReLU()
self.fc1 = nn.Linear(768, 3072)
self.fc2 = nn.Linear(3072, 768)

# forward
x = self.activation_fn(self.fc1(x))
x = self.fc2(x)
```
replacement code :
```python
# init
self.moe_ff = FMoETransformerMLP(num_expert=1, d_model=768, d_hidden=3072, top_k=1, activation=torch.nn.ReLU())

# forward
x=self.moe_ff(x)
```

**Comment by laekov** [comment]
Because although you only have 1 expert, the gate is still there, which is a linear layer of `768x1`. Also, there are some other expert selection counting and other stuff that may slow down `FMoETransformerMLP` from a normal 2-layer MLP. A fair comparison should be between `_Expert` class in `fmoe/transformer.py` and your manually implemented MLP.
