### ISSUE TITLE
About additional loss for load balance

### ISSUE THREAD

**Issue by zjujh1995** [laekov/fastmoe#13]
Seems there's no balance loss in this project. Will it be added later? 
BTW, the re-produced G-Shard Transformer is also trained w/o balance loss?

**Comment by xptree** [comment]
@zjujh1995 Thanks for your question!

The load balance loss is in our v0.2 plan (see https://github.com/laekov/fastmoe/issues/11#issuecomment-790518182). We will also expose the gate scores to users which allows for designing new balance loss functions.

As for your second question, both the FMoE-Transformer-XL and the FMoE-GPT are trained without balance loss.

BTW, it would be impossible to reproduce the GShard model, because it was trained on " a web-scale in-house dataset" (Sec 4.2 https://arxiv.org/pdf/2006.16668.pdf) which we have no access.
