### ISSUE TITLE
More GPU number than expert number 

### ISSUE THREAD

**Issue by hanxuel** [laekov/fastmoe#137]
We are developing a fmoe training pipeline with multi gpu training and trying to catch a deadline. In multi gpu training process, you put at least one expert per gpu. 

Is it possible to make the number of expert be larger than number of gpu workers? How could I do it?

Any advice from you will be much appreciated. Looking forward to hearing from you.

**Comment by laekov** [comment]
As I mentioned in the email, you can use data or model parallel for the experts.

For hybrid of expert and data parallelism of experts, refer to the paper _BaGuaLu_ for the ideas. Its implementation involves a little customization of the `DistributedGroupedDataParallel` module, where the experts of the same data parallel group shall be added into a specific group.

For hybrid of expert and model parallelism of experts, we have that implemented with Megatron-LM in version 0.3.0 and later. The hidden size of FFN is reduced from `4h/k` to `4h/kn` where n stands for the ways of model parallel. The output are reduced across the model parallel comm, so that it mathematically equals to the original one.

**Comment by samhavens** [comment]
Sorry for the confusion, but does this mean that this works for N_expert < N_GPU without any customization if one uses the Megatron-LM version?

**Comment by laekov** [comment]
> Sorry for the confusion, but does this mean that this works for N_expert < N_GPU without any customization if one uses the Megatron-LM version?

I mean there is no customization needed for FastMoE >= 0.3.0. Any version of Megatron is fine as long as it works with FastMoE.

**Comment by samhavens** [comment]
Thank you!
