### ISSUE TITLE
export to onnx or torch jit?

### ISSUE THREAD

**Issue by npuichigo** [laekov/fastmoe#62]

**Comment by laekov** [comment]
If you are not using distributed experts, all the operators are implemented using PyTorch's native operators. I think it is possible to export FastMoE's model to ONNX or Torch Script. Otherwise, you may need to write a script and aggregate the experts together. 

BTW, if you are looking for inference system for MoE, you may check out [Harry Chen's work](https://github.com/Harry-Chen/InfMoE) which is elastic and high-performance.
